### ISSUE TITLE
KOSOVO api requests

### ISSUE THREAD

**Issue by Ardian-Hoti** [Virous77/GlobeGraph#1]
Requests to the world bank for Kosovo are being with XKK instead it should be XK 
example :

https://api.worldbank.org/v2/country/XKK/indicator/NY.GDP.PCAP.CD?date=2010:2024&format=json - this doesn't show any data because the code is bad it should be this :

https://api.worldbank.org/v2/country/XK/indicator/NY.GDP.PCAP.CD?date=2010:2024&format=json

**Comment by Virous77** [comment]
Yes i see World Bank API officially supports Alpha-3 codes for in case of few countries looks like it fall for Alpha-2. Fixing it.

**Comment by Ardian-Hoti** [comment]
> Yes i see World Bank API officially supports Alpha-3 codes for in case of few countries looks like it fall for Alpha-3. Fixing it.

Thank you , I appreciate that

**Comment by Virous77** [comment]
@Ardian-Hoti I got the issue actually the package im using for Alpha-3 it give XKK for Kosovo but looks like actual one is XKX which works with world bank.

**Comment by Virous77** [comment]
Fixes.

**Comment by Ardian-Hoti** [comment]
Great job , thanks
